Update zamundanet.yml
Prowlarr/Indexers pull request #152
Opened 2022-03-19 12:08 UTC by MassaCreto

changing incldead to 0, as the returned results from the tracker are limited when the value is 1. Example, when searching with a term and the set value of incldead is 1, the results are 11, when using the value 0, results are 24

2022-03-19 14:02 UTC, bakerboy448 commented
If the torrents are dead and have no seeders then why would one want them returned?

2022-03-19 18:53 UTC, bakerboy448 requested changes
Change this to a configurable setting checkbox for the user in case not all users want to allow dead torrents.

Update the search path accordingly based on the new config setting

2022-03-20 19:08 UTC, MassaCreto commented
Please check the second commit, it introduces this as a drop down option for the indexer

2022-03-21 00:25 UTC, bakerboy448 approved these changes

2022-03-21 12:08 UTC, merged