New: (Indexer) Torrent Ncore
Prowlarr/Indexers pull request #163
Opened 2022-04-02 11:21 UTC by laszlodoczi

- Added yaml based Ncore tracker

2022-04-02 12:09 UTC, bakerboy448 requested changes
See comments from initial review.

Was this tested on a old Prowlarr running Cardigann v2? It appears it would not work with a Prowlarr running Cardigann v2.

Based on the fact description is missing and thus optional, this would at minimum need to v3.   Haven't looked in depth enough to see if it uses any Cardigann v4 or v5 features

- address comments
- move to the correct Prowlarr Cardigann version

2022-04-02 12:09 UTC, bakerboy448 commented on definitions/v2/ncore.yml
> +
Nit no new line

2022-04-02 12:09 UTC, bakerboy448 commented on definitions/v2/ncore.yml
> +
No line breaks between fields

2022-04-02 12:09 UTC, bakerboy448 commented on definitions/v2/ncore.yml
> +
Same as above

2022-04-02 12:09 UTC, bakerboy448 commented on definitions/v2/ncore.yml
> +
Same as above

2022-04-02 12:09 UTC, bakerboy448 commented on definitions/v2/ncore.yml
> +
Same as above

2022-04-02 12:35 UTC, laszlodoczi commented
> See comments from initial review.
> 
> Was this tested on a old Prowlarr running Cardigann v2? It appears it would not work with a Prowlarr running Cardigann v2.
> 
> Based on the fact description is missing and thus optional, this would at minimum need to v3. Haven't looked in depth enough to see if it uses any Cardigann v4 or v5 features
> 
>     * address comments
> 
>     * move to the correct Prowlarr Cardigann version

I think I used a v2 as a base.
Moved the file into v5, so there should be no issues with versions. Is this fine?

2022-04-02 17:24 UTC, bakerboy448 commented
v2 _may_ be fine

v3 should be the safest bet, so swap that real quick and we'll be all set.

and v5 is only in nightly at this point and this one doesn't seem to have any v5 only features ;)

2022-04-02 17:29 UTC, laszlodoczi commented
@bakerboy448 done!

2022-04-02 17:36 UTC, Qstick commented
Seems fine here

2022-04-02 17:42 UTC, bakerboy448 approved these changes

2022-04-02 17:42 UTC, merged

2022-11-01 15:25 UTC, bohemtucsok commented
Hi 

Ncore torrent problem 

Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

anyone have any ideas?

2022-11-01 15:28 UTC, bakerboy448 commented
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

https://wiki.servarr.com/prowlarr/faq#prowlarr-will-not-sync-x-indexer-to-app