Upgrade YGGTorrent
Prowlarr/Indexers pull request #167
Opened 2022-04-10 17:17 UTC by anthonyraymond

Add new domain for YGGTorrent

2022-04-11 12:39 UTC, bakerboy448 requested changes
- v1 definitions are not supported; revert this change
- don't just overwrite the existing URL, move it to legacy links if it's no longer valid at all and then add the new URL I it's place. Alternatively if it's simply a new alternative URL just add it as another option below the existing entry

2022-04-11 12:43 UTC, foux commented
> * v1 definitions are not supported; revert this change
> * don't just overwrite the existing URL, move it to legacy links if it's no longer valid at all and then add the new URL I it's place. Alternatively if it's simply a new alternative URL just add it as another option below the existing entry

I agree for the first part, but unless I'm reading it wrong, he already moved the `.re` (which is not valid anymore) to the legacy links, no?

2022-04-11 12:47 UTC, bakerboy448 commented
> > * v1 definitions are not supported; revert this change
> 
> > * don't just overwrite the existing URL, move it to legacy links if it's no longer valid at all and then add the new URL I it's place. Alternatively if it's simply a new alternative URL just add it as another option below the existing entry
> 
> 
> 
> I agree for the first part, but unless I'm reading it wrong, he already moved the `.re` (which is not valid anymore) to the legacy links, no?

Ah pre-coffee problems and used to the legacy links being appended and not prepended,  can that legacy link be swapped to the bottom as well otherwise it'll be a pain when pulling future jackett updates

2022-04-11 17:45 UTC, bakerboy448 commented
Fixes https://github.com/Prowlarr/Prowlarr/issues/948#issuecomment-1095339241

2022-04-11 17:47 UTC, foux commented
@anthonyraymond are you sure the new URL shouldn't be https://www5.yggtorrent.la ? I think that is the correct one. Did you test it?

2022-04-11 17:48 UTC, bakerboy448 commented on definitions/v3/yggtorrent.yml
> +  - https://yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-11 17:49 UTC, bakerboy448 commented on definitions/v2/yggcookie.yml
> +  - https://yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-11 17:49 UTC, bakerboy448 commented on definitions/v2/yggtorrent.yml
> +  - https://yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-11 17:49 UTC, bakerboy448 commented on definitions/v3/yggcookie.yml
> +  - https://yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-11 17:50 UTC, bakerboy448 requested changes
s/b https://www5.yggtorrent.la/

2022-04-11 19:39 UTC, anthonyraymond commented
@bakerboy448 Everything should be alright now, and i just squashed the commits

2022-04-11 19:41 UTC, foux commented
> @bakerboy448 Everything should be alright now, and i just squashed the commits

Did you checked it with www3? Because on my side it worked only with www5. It might have been a temporary glitch, but you have to be sure (or add several URLs)

2022-04-11 20:42 UTC, bakerboy448 commented
> > @bakerboy448 Everything should be alright now, and i just squashed the commits
> 
> Did you checked it with www3? Because on my side it worked only with www5. It might have been a temporary glitch, but you have to be sure (or add several URLs)

Jackett also pushed with ww5

2022-04-11 21:54 UTC, bakerboy448 requested changes

2022-04-11 21:54 UTC, bakerboy448 commented on definitions/v2/yggcookie.yml
> +  - https://www3.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/ 
```

2022-04-11 21:54 UTC, bakerboy448 commented on definitions/v2/yggtorrent.yml
> +  - https://www3.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/ 
```

2022-04-11 21:54 UTC, bakerboy448 commented on definitions/v3/yggcookie.yml
> +  - https://www3.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-11 21:54 UTC, bakerboy448 commented on definitions/v3/yggtorrent.yml
> +  - https://www3.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```

2022-04-12 00:35 UTC, anthonyraymond commented
@foux You were right, how did you guessed that it was www5? The website Q&A tells that it's www3

@bakerboy448 done

2022-04-12 00:37 UTC, bakerboy448 requested changes
Quick fixup

2022-04-12 00:37 UTC, bakerboy448 commented on definitions/v2/yggtorrent.yml
> +  - https://www5.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/
```
Trailing space

2022-04-12 00:37 UTC, bakerboy448 commented on definitions/v2/yggcookie.yml
> +  - https://www5.yggtorrent.la/
```suggestion
  - https://www5.yggtorrent.la/ 
```
Trailing space

2022-04-14 00:24 UTC, bakerboy448 approved these changes

2022-04-14 00:24 UTC, merged